structname: "{{.InterfaceName}}"
filename: "{{.InterfaceName | snakecase}}.go"
pkgname: mocks
template: testify
dir: "{{.InterfaceDir}}/mocks"
packages:
  github.com/brunoribeiro127/gobin/internal:
    interfaces:
      BinaryManager:
      ExecCombinedOutput:
      ExecRun:
      System:
      Toolchain:
      Workspace:
