# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

silent: true

vars:
  PACKAGES:
    sh: |
      go list github.com/brunoribeiro127/gobin/... \
        | {{if eq "windows" OS}}findstr /V{{else}}grep -v{{end}} mocks
  INTERNAL_PACKAGES:
    sh: |
      go list github.com/brunoribeiro127/gobin/internal... \
        | {{if eq "windows" OS}}findstr /V{{else}}grep -v{{end}} mocks

tasks:
  build:
    cmds:
      - cmd: CGO_ENABLED=0 go build -v -trimpath -ldflags="-s -w" -o ./bin/gobin github.com/brunoribeiro127/gobin/cmd/gobin
        platforms: [darwin, linux]
      - cmd: CGO_ENABLED=0 go build -v -trimpath -ldflags="-s -w" -o ./bin/gobin.exe github.com/brunoribeiro127/gobin/cmd/gobin
        platforms: [windows]

  check:
    deps:
      - fmt
      - vet
      - lint
      - build
      - test
      - vulncheck

  clean:
    cmds:
      - cmd: rm -rf ./bin ./coverage ./dist
        platforms: [darwin, linux]
      - cmd: |
          powershell -Command "
            if (Test-Path .\bin) { Remove-Item -Recurse -Force .\bin }
            if (Test-Path .\coverage) { Remove-Item -Recurse -Force .\coverage }
            if (Test-Path .\dist) { Remove-Item -Recurse -Force .\dist }
          "
        platforms: [windows]

  coverage:
    cmds:
      - cmd: open ./coverage/coverage.html
        platforms: [darwin]
      - cmd: xdg-open ./coverage/coverage.html
        platforms: [linux]
      - cmd: powershell -Command "Invoke-Item .\coverage\coverage.html"
        platforms: [windows]

  fmt:
    cmd: go fmt ./...

  install:
    cmd: CGO_ENABLED=0 go install -trimpath -ldflags="-s -w" github.com/brunoribeiro127/gobin/cmd/gobin

  install-dev-tools:
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.1
      - go install github.com/vektra/mockery/v3@v3.5.2
      - go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

  lint:
    cmd: golangci-lint run

  mockery:
    cmd: mockery

  run:
    cmd: go run cmd/gobin/main.go {{.CLI_ARGS}}

  test:
    cmds:
      - cmd: mkdir -p coverage
        platforms: [darwin, linux]
      - cmd: powershell -Command "New-Item -ItemType Directory -Path .\coverage -Force"
        platforms: [windows]
      - go clean -testcache
      - go test -coverprofile=coverage/coverage.txt -covermode count {{ catLines .INTERNAL_PACKAGES }}
      - go tool cover -func coverage/coverage.txt
      - go tool cover -html coverage/coverage.txt -o coverage/coverage.html

  tidy:
    cmd: go mod tidy

  vet:
    cmd: go vet {{catLines .PACKAGES }}

  vulncheck:
    cmd: govulncheck ./...
