name: CI

on:
  push:
    branches:
      - main
    paths:
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
  pull_request:
    paths:
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v2.4.0
      GOVULNCHECK_VERSION: v1.1.4
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@${{ env.GOVULNCHECK_VERSION }}
      - name: Install dependencies
        run: go mod download
      - name: Check go.mod and go.sum files
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build ./...
      - name: Test
        run: |
          INTERNAL_PACKAGES=$(go list ./internal/... | grep -v mocks)
          go test -coverprofile=coverage.txt -covermode=count $INTERNAL_PACKAGES
          go tool cover -func=coverage.txt
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Check vulnerabilities
        run: govulncheck ./...
        continue-on-error: true
